#stage 1: Build
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the app
COPY . .

# Stage 2: Runtime (smaller image)
FROM node:22-alpine

WORKDIR /app

# Copy only the built app and dependencies from build stage
COPY --from=build /app /app

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "start"]

