version: '3.9'


services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ubuntu
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./database/mysql-init:/docker-entrypoint-initdb.d

      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  nodejs:
    image: saviomathew/docker-njs-mysql:nodejs-v5 
    container_name: nodejs_ubuntu
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql_ubuntu
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydb
    expose:
      - 3000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - nodejs
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network


networks:
  app-network:

volumes:
  db_data:
